name: SwiftShader Builds

on: [push, pull_request]

env:
  # Ideally use a commit that's verified to work well elsewhere (Arch
  # swiftshader-git package, for example)
  COMMIT: 2afc8c9

# Mostly just copied from here, with ES1 disabled:
# https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=swiftshader-git
jobs:
   ubuntu-gles:
     name: GLES
     runs-on: ubuntu-24.04
     strategy:
       matrix:
         # On 16.04 it uses GCC 5, not GCC 4.8, because it can't build on that
         # one. That's fine however, there are no issues when linking Magnum
         # built with GCC 4.8 against SwiftShader built with GCC 5.
         target-os: [android]
         target-cpu: [arm64]
     steps:
     - name: Install Ninja
       uses: seanmiddleditch/gha-setup-ninja@v3
     - name: Clone SwiftShader
       uses: actions/checkout@v2
       with:
         repository: google/swiftshader
         ref: ${{ env.COMMIT }}
         path: swiftshader
         # Yeah, I know, but the repo has no tags, and we use number of commits
         # for SWIFTSHADER_VERSION.
         fetch-depth: 0
     - name: Init & update submodules, fetch version
       run: |
         git -C swiftshader -c submodule."third_party/git-hooks".update=none submodule update --init --recursive
         SWIFTSHADER_VERSION="r$(git -C swiftshader rev-list --count HEAD).$(git -C swiftshader rev-parse --short=10 HEAD)"
         echo "version: $SWIFTSHADER_VERSION"
         echo "SWIFTSHADER_VERSION=$SWIFTSHADER_VERSION" >> $GITHUB_ENV
     - name: Build & install Release
       run: |
         cmake \
           -G Ninja \
           -DCMAKE_BUILD_TYPE=Release \
           -DSWIFTSHADER_BUILD_GLES_CM=OFF \
           -DSWIFTSHADER_BUILD_GLESv2=ON \
           -DSWIFTSHADER_BUILD_VULKAN=ON \
           -DSWIFTSHADER_BUILD_PVR=OFF \
           -DSWIFTSHADER_BUILD_TESTS=OFF \
           -DSWIFTSHADER_WARNINGS_AS_ERRORS=OFF \
           -S swiftshader -B build
         ninja -C build
         install -dm755 install/lib
         install -m755 -t install/lib \
           build/libEGL.so \
           build/libGLESv2.so \
           build/libvk_swiftshader.so
         install -dm755 install/share/vulkan/icd.d/
         install -m644 -t install/share/vulkan/icd.d/ \
           build/Linux/vk_swiftshader_icd.json
         sed 's#./libvk_swiftshader.so#../../../lib/libvk_swiftshader.so#' \
           -i install/share/vulkan/icd.d/7997cbc34bb2d5db771f0d0b2497aeb665168ed2
     - name: Upload Release artifacts
       uses: actions/upload-artifact@v3
       with:
         name: swiftshader-gles-${{ env.SWIFTSHADER_VERSION }}-${{ matrix.os }}
         path: install

#   ubuntu-vulkan:
#     name: Vulkan, ${{ matrix.os }}
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         # Vulkan libs don't build with GCC 5 on 16.04, use just 18.04
#         os: [ubuntu-20.04]
#     steps:
#     - name: Install Ninja
#       uses: seanmiddleditch/gha-setup-ninja@v3
#     - name: Clone SwiftShader
#       uses: actions/checkout@v2
#       with:
#         repository: google/swiftshader
#         ref: ${{ env.COMMIT }}
#         path: swiftshader
#         # Yeah, I know, but the repo has no tags, and we use number of commits
#         # for SWIFTSHADER_VERSION.
#         fetch-depth: 0
#     - name: Init & update submodules, fetch version
#       run: |
#         git -C swiftshader -c submodule."third_party/git-hooks".update=none submodule update --init --recursive
#         SWIFTSHADER_VERSION="r$(git -C swiftshader rev-list --count HEAD).$(git -C swiftshader rev-parse --short=10 HEAD)"
#         echo "version: $SWIFTSHADER_VERSION"
#         echo "SWIFTSHADER_VERSION=$SWIFTSHADER_VERSION" >> $GITHUB_ENV
#     - name: Configure
#       run: |
#         cmake \
#           -G Ninja \
#           -DCMAKE_BUILD_TYPE=Release \
#           -DSWIFTSHADER_BUILD_GLES_CM=OFF \
#           -DSWIFTSHADER_BUILD_GLESv2=OFF \
#           -DSWIFTSHADER_BUILD_VULKAN=ON \
#           -DSWIFTSHADER_BUILD_PVR=OFF \
#           -DSWIFTSHADER_BUILD_TESTS=OFF \
#           -DSWIFTSHADER_WARNINGS_AS_ERRORS=OFF \
#           -S swiftshader -B build
#     - name: Build
#       run: |
#         ninja -C build
#     - name: Install
#       run: |
#         install -dm755 install/lib
#         install -m755 -t install/lib \
#           build/libvk_swiftshader.so
#         install -dm755 install/share/vulkan/icd.d/
#         install -m644 -t install/share/vulkan/icd.d/ \
#           build/Linux/vk_swiftshader_icd.json
#         sed 's#./libvk_swiftshader.so#../../../lib/libvk_swiftshader.so#' \
#           -i install/share/vulkan/icd.d/7997cbc34bb2d5db771f0d0b2497aeb665168ed2
#     - name: Upload artifacts
#       uses: actions/upload-artifact@v1
#       with:
#         name: swiftshader-vulkan-${{ env.SWIFTSHADER_VERSION }}-${{ matrix.os }}
#         path: install
#       
